### ISSUE TITLE
Bug: firstadmin does not get a TAK package

### ISSUE THREAD

**Issue by benjamsf** [pvarki/python-tak-rmapi#52]
# What
Rasenmaeher firstadmin does not get a TAK package. https://mtls.localmaeher.pvarki.fi:4439/api/v1/instructions/user returns null. 
# Expected function
To get tak zip as an admin enrolled by firstuser code.
# What happened
Didn't get a package, but
- if I enrolled another user, that would get a tak zip, be they regularuser or admin
# When it started to happen
Apparently after tak-rmapi feature upgrades to sync user's admin status to the takserver (?). In the same time, we have had the RM ocsp feature & tak zip feature upgrade rolling out so might be either of these as well.
# Log output
From takrmapi container:
```
2024-04-06 15:25:31 INFO:     172.29.0.8:51462 - "POST /api/v1/clients/fragment HTTP/1.0" 500 Internal Server Error
2024-04-06 15:25:30 [2024-04-06 12:25:30,239][INFO] takrmapi.tak_helpers (115) /app/src/takrmapi/tak_helpers.py:manifest_p12_row:244 | Creating /tmp/ocspbensam_default/atak/rasenmaeher_ca-public.p12
2024-04-06 15:25:31 [2024-04-06 12:25:31,365][INFO] takrmapi.tak_helpers (115) /app/src/takrmapi/tak_helpers.py:manifest_p12_row:252 | Creating /tmp/ocspbensam_default/atak/ocspbensam.p12
2024-04-06 15:25:31 ERROR:    Exception in ASGI application
2024-04-06 15:25:31 Traceback (most recent call last):
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2024-04-06 15:25:31     result = await app(  # type: ignore[func-returns-value]
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-04-06 15:25:31     return await self.app(scope, receive, send)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-04-06 15:25:31     await super().__call__(scope, receive, send)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-04-06 15:25:31     await self.middleware_stack(scope, receive, send)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-04-06 15:25:31     raise exc
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-04-06 15:25:31     await self.app(scope, receive, _send)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-04-06 15:25:31     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-04-06 15:25:31     raise exc
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-04-06 15:25:31     await app(scope, receive, sender)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
2024-04-06 15:25:31     await self.middleware_stack(scope, receive, send)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
2024-04-06 15:25:31     await route.handle(scope, receive, send)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
2024-04-06 15:25:31     await self.app(scope, receive, send)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
2024-04-06 15:25:31     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-04-06 15:25:31     raise exc
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-04-06 15:25:31     await app(scope, receive, sender)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
2024-04-06 15:25:31     response = await func(request)
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
2024-04-06 15:25:31     raw_response = await run_endpoint_function(
2024-04-06 15:25:31   File "/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-04-06 15:25:31     return await dependant.call(**values)
2024-04-06 15:25:31   File "/app/src/takrmapi/api/clientinfo.py", line 22, in client_instruction_fragment
2024-04-06 15:25:31     zip_files = await tak_missionpkg.create_missionpkg()
2024-04-06 15:25:31   File "/app/src/takrmapi/tak_helpers.py", line 163, in create_missionpkg
2024-04-06 15:25:31     zip_file = await self.create_mission_zip(app_version="atak", walk_dir=f"{walk_dir}/atak")
2024-04-06 15:25:31   File "/app/src/takrmapi/tak_helpers.py", line 194, in create_mission_zip
2024-04-06 15:25:31     await self.tak_manifest_extra(rendered_template, tmp_folder)
2024-04-06 15:25:31   File "/app/src/takrmapi/tak_helpers.py", line 233, in tak_manifest_extra
2024-04-06 15:25:31     await self.manifest_p12_row(row, tmp_folder)
2024-04-06 15:25:31   File "/app/src/takrmapi/tak_helpers.py", line 254, in manifest_p12_row
2024-04-06 15:25:31     self.user.certpem, self.user.certkey, self.user.callsign, None, self.user.callsign
2024-04-06 15:25:31   File "/app/src/takrmapi/tak_helpers.py", line 65, in certkey
2024-04-06 15:25:31     raise ValueError("We do not have the private key")
2024-04-06 15:25:31 ValueError: We do not have the private key
````

**Comment by benjamsf** [comment]
Triage: 
- Not critical, as of we don't have any scheduled deployments right now that would have a firstuser that is not either a dev or connected to the devs.

**Comment by rambo** [comment]
Likely same underlying race condition as with https://github.com/pvarki/python-tak-rmapi/issues/50

**Comment by benjamsf** [comment]
Apparently, this does not happen anymore as of d-1.4.1. Got in fine with a firstadmin user. Only what happens is that firstadmin won't get to TAK WebAdmin which is probably because of how takrmapi communicates role changes only when they occur, not initially.

**Comment by benjamsf** [comment]
Fixed with 1.7.3
